    - name: Deploy Changed Lambda Functions
      run: |
        S3_BUCKET=lambda-zips-8207-4071-9509

        for function in ${{ steps.detect.outputs.functions }}; do
          echo "Deploying Lambda function: $function"

          ZIP_NAME="${function}.zip"
          S3_KEY="${function}.zip"
          LAMBDA_FUNCTION_NAME="$function"

          # Create a temp directory for packaging
          mkdir -p temp_lambda

          # Copy contents of the lambda function folder to temp dir
          cp -r $function/* temp_lambda/

          # Zip the contents (not the folder) so the entrypoint is at the root
          cd temp_lambda
          zip -r ../$ZIP_NAME .
          cd ..

          # Upload to S3
          aws s3 cp $ZIP_NAME s3://$S3_BUCKET/$S3_KEY

          # Update Lambda
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --s3-bucket $S3_BUCKET --s3-key $S3_KEY

          # Cleanup
          rm -rf temp_lambda
          rm $ZIP_NAME
        done
